version: '3.8'
services:
   mysql-account-db:
      image: mysql:latest
      restart: always
      ports:
      - 3307:3306
      environment:
         MYSQL_DATABASE: account_DB
         MYSQL_USER: sa
         MYSQL_PASSWORD: password
         MYSQL_ROOT_PASSWORD: password
      networks:
      - bank
   mysql-loan-db:
      image: mysql:latest
      restart: always
      ports:
      - 3308:3306
      environment:
         MYSQL_DATABASE: loan_DB
         MYSQL_USER: sa
         MYSQL_PASSWORD: password
         MYSQL_ROOT_PASSWORD: password
      networks:
      - bank
   mysql-card-db:
      image: mysql:latest
      restart: always
      ports:
      - 3309:3306
      environment:
         MYSQL_DATABASE: card_DB
         MYSQL_USER: sa
         MYSQL_PASSWORD: password
         MYSQL_ROOT_PASSWORD: password
      networks:
      - bank
   zipkin:
      image: openzipkin/zipkin
      mem_limit: 700m
      ports:
      - 9411:9411
      networks:
      - bank
   configserver:
      image: configserver:latest
      mem_limit: 700m
      ports:
      - 8072:8071
      depends_on:
      - zipkin
      environment:
         SPRING_PROFILES_ACTIVE: default
         SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      networks:
      - bank
   eurekaserver:
      image: eurekaserver:latest
      mem_limit: 700m
      ports:
      - 8069:8070
      environment:
         SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      networks:
      - bank
   accounts:
      image: account:latest
      restart: always
      ports:
      - 5051:5050
      - 5052:5050
      depends_on:
      - mysql-account-db
      - configserver
      - eurekaserver
      deploy:
         restart_policy:
            condition: on-failure
            delay: 30s
            max_attempts: 4
            window: 120s
      command: sh -c './wait-for mysql-account-db:3306 -- npm start'
      environment:
         SPRING_PROFILES_ACTIVE: docker
         SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
         EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
         SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      networks:
      - bank
   loans:
      image: loan:latest
      restart: always
      ports:
      - 6061:6060
      - 6062:6060
      depends_on:
      - mysql-loan-db
      - configserver
      - eurekaserver
      deploy:
         restart_policy:
            condition: on-failure
            delay: 30s
            max_attempts: 4
            window: 120s
      command: sh -c './wait-for mysql-loan-db:3306 -- npm start'
      environment:
         SPRING_PROFILES_ACTIVE: docker
         SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
         EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
         SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      networks:
      - bank
   cards:
      image: card:latest
      restart: always
      ports:
      - 7071:7070
      - 7072:7070
      depends_on:
      - mysql-card-db
      - configserver
      - eurekaserver
      deploy:
         restart_policy:
            condition: on-failure
            delay: 30s
            max_attempts: 4
            window: 120s
      command: sh -c './wait-for mysql-card-db:3306 -- npm start'
      environment:
         SPRING_PROFILES_ACTIVE: docker
         SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
         EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
         SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      networks:
      - bank
   gatewayserver:
      image: gatewayserver:latest
      restart: always
      ports:
      - 8074:8073
      depends_on:
      - configserver
      - eurekaserver
      - account
      - loan
      - card
      deploy:
         restart_policy:
            condition: on-failure
            delay: 45s
            max_attempts: 4
            window: 180s
      environment:
         SPRING_PROFILES_ACTIVE: default
         SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
         EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
         SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      networks:
      - bank
networks:
   bank: null